version: '2'

services:
  db:
    image: centos/postgresql-95-centos7
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    networks:
      - default
  core:
    image: almightycore/almighty-core:latest
    environment:
      ALMIGHTY_POSTGRES_HOST: db
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db
