# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


required = [
  "github.com/golang/lint/golint",
  "github.com/fzipp/gocyclo",
  "github.com/goadesign/goa/cors",
  "github.com/goadesign/goa/encoding/form",
  "github.com/goadesign/goa/goagen",
  "github.com/goadesign/goa/goagen/codegen",
  "github.com/goadesign/goa/goagen/gen_app",
  "github.com/goadesign/goa/goagen/gen_controller",
  "github.com/goadesign/goa/goagen/gen_swagger",
  "github.com/goadesign/goa/goagen/gen_client",
  "github.com/goadesign/goa/goagen/gen_js",
  "github.com/goadesign/goa/goagen/utils",
  "github.com/goadesign/goa/goatest",
  "github.com/fabric8-services/fabric8-auth/design",
  "github.com/fabric8-services/fabric8-auth/token/jwk",
  "github.com/fabric8-services/fabric8-notification/design",
  "github.com/fabric8-services/fabric8-tenant/design",
  "github.com/jteeuwen/go-bindata/go-bindata",
  "github.com/jstemmer/go-junit-report",
  "github.com/wadey/gocovmerge",
  "github.com/pilu/fresh",
]
    
ignored = [
  "github.com/fabric8-services/fabric8-auth/account/tenant",
]

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "5.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.0.0"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/hawkular/hawkular-client-go"
  version = "0.6.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "0.11.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/asaskevich/govalidator.v4"
  version = "4.0.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  name = "github.com/golang/lint"
  revision = "master"
  
[[constraint]]
  name = "github.com/fzipp/gocyclo"
  revision = "master"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "v3.0.7"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-auth"
  revision = "f717b4f4244a9d6fd31a54e7231a11eff14fa695"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-notification"
  revision = "master"

[[constraint]]
  name = "github.com/fabric8-services/fabric8-tenant"
  revision = "master"

[[constraint]]
  name = "github.com/jstemmer/go-junit-report"
  revision = "master"

[[constraint]]
  name = "github.com/wadey/gocovmerge"
  revision = "master"

[[constraint]]
  name = "github.com/pilu/fresh"
  revision = "9c0092493eff2825c3abf64e087b3383dec939c3"

[prune]
  go-tests = true
  unused-packages = true
