kind: Template
apiVersion: v1
metadata:
  name: core
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: core
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    keycloak.realm: ZmFicmljOAo=
    keycloak.secret: Cg==
    token.publickey: Cg==
    tenantsvc.url: aHR0cDovL2Y4dGVuYW50Ojgw
    sentry.dsn: aHR0cDovL2I2YzBlZTdjN2ZhNTQ0MzU5YmUzZTU1Zjk0YzJmODg5OjkzMGExZWQ0OWFmYzQzNjZhMTM2OWIwYzUyYmI4YmZkQHNlbnRyeS5zZW50cnk6OTAwMC8y
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: core
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    chestarter.url: http://che-starter:10000
    notification.serviceurl: ""
    auth.serviceurl: https://auth.openshift.io
    osoproxy.url: http://f8osoproxy
    toggles.serviceurl: http://f8toggles-service
    redirect.valid: ".*"
    openshift.tenant.masterurl: https://openshift.local/
    auth_notapproved_redirect: ""
    feature.workitem.remote: "false"
    deployments.serviceurl: "http://core"
    codebase.serviceurl: "http://core"
